[package]
name = "qqr"
version = "0.1.0"
edition = "2021"

[dependencies]
qrcode = {version = "0.14.1",  default-features = false, features = ["image", "svg"]}
rocket = "0.5.1"
image = {version = "0.25.5", default-features = false, features = ["png"]}

[[bin]]
name = "qqr"
path = "src/main.rs"